modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"
issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="lightmeals"
version="0.1"
displayName="Light Meals"
updateJSONURL="https://gitee.com/hashtag233/mc-mod-services/raw/master/light-meals-upd.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/light-meals"
logoFile="examplemod.png"
credits="All credit to Lellson8 for open sourcing his Food Expansion and the full permission. "
authors="Hashtag233, Ender_Ruier"
description='''
Add numerous foods within the vanilla framework.
'''
[[dependencies.lightmeals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
